##### After Preprocessing

In [23]:
import pandas as pd
import numpy as np
import random

from sklearn.neighbors import DistanceMetric
from math import radians

In [24]:
Data = pd.read_csv('Final_results.csv')

In [25]:
Data.head()

Geometri  Latitude  Longitude                              City  \
0  northeast  0.048731   1.719746                Tao Silalahi hotel   
1  northeast  0.046310   1.717087         "Sicike-cike" Nature Park   
2  northeast  0.047703   1.717085  Taman Wisata Iman Sitinjo, Dairi   
3  northeast  0.047753   1.717110  Air Terjun Jembatan Lae Pendaroh   
4  northeast  0.047099   1.715783        Peak Tree House Sidikalang   

              Biaya  21-Dec-19  22-Dec-19  23-Dec-19  24-Dec-19  25-Dec-19  \
0             IDR -         24         26         27         27         27   
1             IDR -         24         26         27         27         27   
2   IDR 300,000.00          23         25         26         26         26   
3    IDR 20,000.00          23         25         26         26         26   
4   IDR 762,300.00          23         25         26         26         26   

   26-Dec-19  27-Dec-19  28-Dec-19  
0         26         27         26  
1         26         27         26  
2         25         26         26  
3         25         26         26  
4         25         26         26

In [26]:
#Data.loc[153]

In [27]:
Data = Data.assign(ID_City=np.arange(len(Data))).reset_index(drop=True)

In [28]:
Data.head()

Geometri  Latitude  Longitude                              City  \
0  northeast  0.048731   1.719746                Tao Silalahi hotel   
1  northeast  0.046310   1.717087         "Sicike-cike" Nature Park   
2  northeast  0.047703   1.717085  Taman Wisata Iman Sitinjo, Dairi   
3  northeast  0.047753   1.717110  Air Terjun Jembatan Lae Pendaroh   
4  northeast  0.047099   1.715783        Peak Tree House Sidikalang   

              Biaya  21-Dec-19  22-Dec-19  23-Dec-19  24-Dec-19  25-Dec-19  \
0             IDR -         24         26         27         27         27   
1             IDR -         24         26         27         27         27   
2   IDR 300,000.00          23         25         26         26         26   
3    IDR 20,000.00          23         25         26         26         26   
4   IDR 762,300.00          23         25         26         26         26   

   26-Dec-19  27-Dec-19  28-Dec-19  ID_City  
0         26         27         26        0  
1         26         27         26        1  
2         25         26         26        2  
3         25         26         26        3  
4         25         26         26        4

In [29]:
Data['ID_City'].head()

0    0
1    1
2    2
3    3
4    4
Name: ID_City, dtype: int32

In [30]:
x = Data.ID_City
bebas = [x]

for x in range (10): 
    bebas[x] = [x for x  in range(10)]
    bebas.append(random.shuffle(bebas[x]))
    print(np.random.random_integers(1, 10))

5
4
6
6
1
5
6
10
8
3


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  import sys


In [31]:
import sys

x = Data.ID_City
bebas = [x]

for x in range (10): 
    bebas[x] = [x for x  in range(10)]
    bebas.append(random.shuffle(bebas[x]))
    a = print(np.random.random_integers(1, len(Data['ID_City']), random.randrange(1,16)))

[133  55 145  93  27  50  14  39 117  78 140  65 109]
[ 13  30  97  14 136  71 101]
[57]
[ 76  79 109 155   3  13  84 100  71 147  60 115 122  95]
[16 57]
[  1  28  43 106 106 134  78  92  53  19 101  92]
[ 59  76  72  97  64   7  94 106  83  17  39]
[ 11  88  52 131 142 108  40  16 142  10 119 131]
[138  94  75  51  29  12  16  24  78 100  31]
[ 31 145 148  95 116 132   1  23  80  44  48]


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: This function is deprecated. Please call randint(1, 156 + 1) instead
  if __name__ == '__main__':


In [32]:
x = Data.ID_City
arr = []
bebas = [x]


bebek = []
for x in range (10): 
    bebas[x] = [x for x  in range(10)]
    bebas.append(random.shuffle(bebas[x]))
    bebek.append(np.random.random_integers(1, len(Data['ID_City']), random.randrange(1,10)))

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: This function is deprecated. Please call randint(1, 156 + 1) instead
  # Remove the CWD from sys.path while we load stuff.


In [33]:
bebek

[array([ 32, 130,  50]),
 array([142,  93,  21,  83,  41]),
 array([ 65,  31, 136,  54,  22,  73,  56,  63]),
 array([145,   2,  47,  69, 111, 120]),
 array([151,  97, 104, 137, 122, 148,  50, 123]),
 array([69]),
 array([149]),
 array([136,  88, 128,  19,  46,  30,   2]),
 array([141, 149,  32, 155, 114,  63]),
 array([ 5, 20, 74])]

In [34]:
Data1 = Data['Latitude'].loc[Data['ID_City'] == bebek[1][1]] 
Data2 = Data['Longitude'].loc[Data['ID_City'] == bebek[1][1]]
  
print(Data1)
print(Data2)

93    0.046781
Name: Latitude, dtype: float64
93    1.725044
Name: Longitude, dtype: float64


In [35]:
Data.head()

Geometri  Latitude  Longitude                              City  \
0  northeast  0.048731   1.719746                Tao Silalahi hotel   
1  northeast  0.046310   1.717087         "Sicike-cike" Nature Park   
2  northeast  0.047703   1.717085  Taman Wisata Iman Sitinjo, Dairi   
3  northeast  0.047753   1.717110  Air Terjun Jembatan Lae Pendaroh   
4  northeast  0.047099   1.715783        Peak Tree House Sidikalang   

              Biaya  21-Dec-19  22-Dec-19  23-Dec-19  24-Dec-19  25-Dec-19  \
0             IDR -         24         26         27         27         27   
1             IDR -         24         26         27         27         27   
2   IDR 300,000.00          23         25         26         26         26   
3    IDR 20,000.00          23         25         26         26         26   
4   IDR 762,300.00          23         25         26         26         26   

   26-Dec-19  27-Dec-19  28-Dec-19  ID_City  
0         26         27         26        0  
1         26         27         26        1  
2         25         26         26        2  
3         25         26         26        3  
4         25         26         26        4

In [36]:
Data.loc[121]

Geometri          northeast
Latitude          0.0407576
Longitude           1.72644
City            Muara Nauli
Biaya         IDR 5,000.00 
21-Dec-19                29
22-Dec-19                28
23-Dec-19                29
24-Dec-19                30
25-Dec-19                29
26-Dec-19                29
27-Dec-19                30
28-Dec-19                31
ID_City                 121
Name: 121, dtype: object

In [40]:
Data_ = Data.sample(10, replace = True)

Data_

Geometri  Latitude  Longitude  \
7    northeast  0.047901   1.715924   
73   northeast  0.046781   1.725044   
125  northeast  0.035450   1.727545   
107  northeast  0.053758   1.729282   
127  northeast  0.036266   1.726945   
74   northeast  0.045705   1.725666   
29   northeast  0.038621   1.719917   
111  northeast  0.047464   1.730332   
1    northeast  0.046310   1.717087   
47   northeast  0.056350   1.719849   

                                                  City             Biaya  \
7                                       Taman Rekreasi     IDR 5,000.00    
73   Batu Kursi Raja Siallagan ( Stone Chair of Kin...     IDR 5,000.00    
125                         Thermal Baths U.S.K Hineni     IDR 8,000.00    
107                                Bah Salak Waterfall     IDR 3,500.00    
127                                Air Panas Sipoholon     IDR 5,000.00    
74                 Parhallow viewpoint and coffee shop   IDR 350,000.00    
29                  objek wisata baronjong aek sirahar    IDR 20,000.00    
111                               Niagara sipitu Tikka     IDR 5,000.00    
1                            "Sicike-cike" Nature Park             IDR -   
47                                 TWA Lau Debuk-debuk             IDR -   

     21-Dec-19  22-Dec-19  23-Dec-19  24-Dec-19  25-Dec-19  26-Dec-19  \
7           23         25         26         26         26         25   
73          25         27         28         28         28         27   
125         23         23         24         25         25         25   
107         28         29         31         31         31         29   
127         22         23         24         24         23         23   
74          25         27         28         28         28         27   
29          23         24         24         24         24         24   
111         25         27         28         28         28         27   
1           24         26         27         27         27         26   
47          20         21         23         22         23         22   

     27-Dec-19  28-Dec-19  ID_City  
7           26         26        7  
73          28         28       73  
125         24         24      125  
107         30         30      107  
127         23         23      127  
74          28         28       74  
29          25         26       29  
111         28         28      111  
1           27         26        1  
47          23         23       47

In [49]:
arr = []
for i in Data_["City"]:
    arr.append(i)
arr

['Taman Rekreasi',
 'Batu Kursi Raja Siallagan ( Stone Chair of King Siallagan )',
 'Thermal Baths U.S.K Hineni',
 'Bah Salak Waterfall',
 'Air Panas Sipoholon',
 'Parhallow viewpoint and coffee shop',
 'objek wisata baronjong aek sirahar',
 'Niagara sipitu Tikka',
 '"Sicike-cike" Nature Park',
 'TWA Lau Debuk-debuk']

In [50]:
initial_state = []
def Initial_State_Awal(arr):
    for i in range (len(arr)):
        x = random.choice(arr)
        if x not in initial_state:
            initial_state.append(x)
    return initial_state 

In [51]:
Awal = Initial_State_Awal(arr)
Awal

['Air Panas Sipoholon',
 'objek wisata baronjong aek sirahar',
 '"Sicike-cike" Nature Park',
 'Thermal Baths U.S.K Hineni',
 'TWA Lau Debuk-debuk']

In [58]:
# for item in df["Tempat Wisata"]["Pasir Putih Parbaba"]:
#     print(item)
test = []
for i in range(len(Data_)):
    temp = Data_.iloc[i]["City"]
    print(str(i) + " = " + temp)
    if temp in Awal:
        test.append((temp,(Data_.iloc[i]["Latitude"],Data_.iloc[i]["Longitude"])))   

0 = Taman Rekreasi
1 = Batu Kursi Raja Siallagan ( Stone Chair of King Siallagan )
2 = Thermal Baths U.S.K Hineni
3 = Bah Salak Waterfall
4 = Air Panas Sipoholon
5 = Parhallow viewpoint and coffee shop
6 = objek wisata baronjong aek sirahar
7 = Niagara sipitu Tikka
8 = "Sicike-cike" Nature Park
9 = TWA Lau Debuk-debuk


In [59]:
test

[('Thermal Baths U.S.K Hineni', (0.03544994, 1.727544543)),
 ('Air Panas Sipoholon', (0.036266385, 1.726945295)),
 ('objek wisata baronjong aek sirahar', (0.038620995, 1.719916979)),
 ('"Sicike-cike" Nature Park', (0.046310397999999996, 1.7170872209999999)),
 ('TWA Lau Debuk-debuk', (0.056349509000000006, 1.7198486119999998))]

In [60]:
arr1= []
def Encoding(Awal):
    arr1.clear()
    for i in range(len(arr)):
        cek = 0
        for x in range(len(Awal)):
            if arr[i] == Awal[x]:
                cek = 1
                break  
        arr1.append(cek)

    return arr1

In [65]:
arr2= []
def Encoding_index(Awal):
    arr2.clear()
    for i in range(len(Awal)):
        for x in range(len(arr)):
            if Awal[i] is arr[x]:
                arr2.append(x+1)
                break

    return arr2

In [66]:
Itinerary = []
Encoding_index(Awal)


[5, 7, 9, 3, 10]

In [68]:
for i in range (5):
    Itinerary = random.sample(arr, N)
    init_ = Encoding(Itinerary)
    init__ = Encoding_index(Itinerary)
    print(Itinerary)
    print(init_)
    
    print("\n")
    init_.clear()
    init__.clear()
    Itinerary.clear()

['Niagara sipitu Tikka', 'Thermal Baths U.S.K Hineni', 'Taman Rekreasi', 'TWA Lau Debuk-debuk', 'Parhallow viewpoint and coffee shop', 'Air Panas Sipoholon', 'Batu Kursi Raja Siallagan ( Stone Chair of King Siallagan )']
[1, 1, 1, 0, 1, 1, 0, 1, 0, 1]


['Bah Salak Waterfall', 'Taman Rekreasi', '"Sicike-cike" Nature Park', 'Niagara sipitu Tikka', 'TWA Lau Debuk-debuk', 'Parhallow viewpoint and coffee shop', 'Thermal Baths U.S.K Hineni']
[1, 0, 1, 1, 0, 1, 0, 1, 1, 1]


['"Sicike-cike" Nature Park', 'Bah Salak Waterfall', 'Air Panas Sipoholon', 'Batu Kursi Raja Siallagan ( Stone Chair of King Siallagan )', 'Niagara sipitu Tikka', 'Parhallow viewpoint and coffee shop', 'Taman Rekreasi']
[1, 1, 0, 1, 1, 1, 0, 1, 1, 0]


['Taman Rekreasi', '"Sicike-cike" Nature Park', 'Batu Kursi Raja Siallagan ( Stone Chair of King Siallagan )', 'objek wisata baronjong aek sirahar', 'TWA Lau Debuk-debuk', 'Niagara sipitu Tikka', 'Air Panas Sipoholon']
[1, 1, 0, 0, 1, 0, 1, 1, 1, 1]


['TWA Lau Debuk-debuk